# fly.toml app configuration file generated for wajha-backend on 2026-05-17T22:15:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wajha-backend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'
  release_command = "echo 'wajha-backend release ok'"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
